plugins {
    id("java")
    kotlin("jvm")
    id("maven-publish")
    id("com.gradleup.shadow") version "9.3.2"
}

group = "dev.efelleto"
version = "1.0.16"

repositories {
    mavenCentral()
    maven("https://hub.spigotmc.org/nexus/content/groups/public/")
}

dependencies {
    val ktor_version = "2.3.12"

    api(project(":Core"))

    compileOnly("org.spigotmc:spigot-api:1.8.8-R0.1-SNAPSHOT")

    // Ktor is bundled and relocated inside the fat jar
    implementation("io.ktor:ktor-client-core:$ktor_version")
    implementation("io.ktor:ktor-client-cio:$ktor_version")
    implementation("io.ktor:ktor-client-content-negotiation:$ktor_version")
    implementation("io.ktor:ktor-serialization-gson:$ktor_version")

    // Kotlin is excluded from the fat jar  (the server must provide it via a Kotlin plugin)
    compileOnly(kotlin("stdlib"))
    compileOnly(kotlin("reflect"))

    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

// Java 8 support
java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinJvmCompile>().configureEach {
    compilerOptions {
        jvmTarget.set(org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_1_8)
    }
}

tasks.named<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>("shadowJar") {
    archiveClassifier.set("")
    mergeServiceFiles()

    // Relocate third-party libs to avoid classpath conflicts
    relocate("io.ktor", "dev.efelleto.diogenes.libs.ktor")
    relocate("com.google.gson", "dev.efelleto.diogenes.libs.gson")
    relocate("io.netty", "dev.efelleto.diogenes.libs.netty")

    // Kotlin and kotlinx are NOT relocated -> doing so breaks kotlin-reflect's
    // internal resource loading (kotlin_builtins), causing ExceptionInInitializerError
    dependencies {
        exclude(dependency("org.jetbrains.kotlin:kotlin-stdlib"))
        exclude(dependency("org.jetbrains.kotlin:kotlin-stdlib-jdk8"))
        exclude(dependency("org.jetbrains.kotlin:kotlin-stdlib-jdk7"))
        exclude(dependency("org.jetbrains.kotlin:kotlin-reflect"))
        exclude(dependency("org.jetbrains.kotlinx:kotlinx-coroutines-core"))
        exclude(dependency("org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm"))
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            // Uses the JAR generated by shadow as the official artifact
            artifact(tasks.named("shadowJar"))
            artifactId = "SDK"
        }
    }
}