name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # Certifique-se de que sua branch principal é a main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: Website/package-lock.json # Indica onde está o lock

      - name: Install dependencies
        run: cd Website && npm install

      - name: Build website
        run: cd Website && npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Website/build # Aponta para a pasta build dentro de Website